server:
  port: 8083

spring:
  application:
    name: OPPORTUNITY-MANAGEMENT
  cloud:
    stream:
      bindings:
        contactDeleted:
          destination: contact-deleted
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      contactManagementService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
      userService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
