server:
  port: 8083

spring:
  application:
    name: OPPORTUNITY-MANAGEMENT
  cloud:
    stream:
      bindings:
        contactDeleted:
          destination: contact-deleted
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/