server:
  port: 8082

spring:
  application:
    name: CONTACT-MANAGEMENT
  cloud:
    stream:
      bindings:
        contactDeleted:
          destination: contact-deleted

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/