spring:
 cloud:
   gateway:
     routes:
       - id: swiggy-app
         uri: lb://SWIGGY-APP
         predicates:
           - Path=/swiggy/**
         filters:
           - AuthenticationFilter


       - id: restaurant-service
         uri: lb://RESTAURANT-SERVICE
         predicates:
           - Path=/restaurant/**
         filters:
           - AuthenticationFilter

       - id: identity-service
         uri: lb://IDENTITY-SERVICE
         predicates:
           - Path=/auth/**
       - id: contact-service
         uri: lb://CONTACT-MANAGEMENT
         predicates:
           - Path=/api/contact-management/**
       - id: opportunity-service
         uri: lb://OPPORTUNITY-MANAGEMENT
         predicates:
           - Path=/api/opportunity-management/**


 application:
   name: CRM-GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/